version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: 'rdspassword'
      MYSQL_ROOT_PASSWORD: 'rdspassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: